
# File: .github/workflows/workflow.yml

on: [push]

name: CI FrontEnd App

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - uses: azure/docker-login@v1
      with:
        login-server: eultengodevacr01.azurecr.io
        username: 97f36c8f-940d-4c8c-813e-e9af0f248f08
        password: ${{ secrets.TF_ARM_CLIENT_SECRET }}
    
    - run: |
          docker build . -t eultengodevacr01.azurecr.io/frontend:${{ github.sha }}
                   
    - name: Container image scan
      uses: Azure/container-scan@v0.1
      with:
        image-name: eultengodevacr01.azurecr.io/frontend:${{ github.sha }}
        username: 97f36c8f-940d-4c8c-813e-e9af0f248f08
        password: ${{ secrets.TF_ARM_CLIENT_SECRET }}
    
    - run: |
         docker push eultengodevacr01.azurecr.io/frontend:${{ github.sha }}
