
# File: .github/workflows/workflow.yml

on: [push]

name: CI FrontEnd App

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - uses: azure/docker-login@v1
      with:
        login-server: eultengodevacr01.azurecr.io
        username: 97f36c8f-940d-4c8c-813e-e9af0f248f08
        password: ${{ secrets.TF_ARM_CLIENT_SECRET }}

    - name:  'Automated Version Bump'
      id: version-bump
      uses:  'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        minor-wording:  'add,Adds,new'
        major-wording:  'MAJOR,cut-major'
        patch-wording:  'patch,fixes,fix'     # Providing patch-wording will override commits
                                              # defaulting to a patch bump.
        rc-wording:     'RELEASE,alpha'


    - name: Output Step                             # Optional: Prints the new version
      env:
        NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
      run: echo "new tag $NEW_TAG"

    - run: |
          docker build . -t eultengodevacr01.azurecr.io/frontend:${{ steps.version-bump.outputs.newTag }}
                   
    - name: Container image scan
      uses: Azure/container-scan@v0.1
      with:
        image-name: eultengodevacr01.azurecr.io/frontend:${{ steps.version-bump.outputs.newTag}}
        username: 97f36c8f-940d-4c8c-813e-e9af0f248f08
        password: ${{ secrets.TF_ARM_CLIENT_SECRET }}
    
    - run: |
         docker push eultengodevacr01.azurecr.io/frontend:${{ steps.version-bump.outputs.newTag }}

    - name:  Upgrade Deployment Frontend Image
      uses: actions/checkout@v2.4.2
      with:
         repository: uledwin/rampupk8sdeployment
         ref: feature
         token: ${{ github.token }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - run: |
          git clone https://github.com/uledwin/rampupk8sdeployment.git
          cd rampupk8sdeployment/
          git config user.name github-image-updater
          git config user.email noreply@imageupdater.io
          git checkout --force feature
          sed -i 's/image: uledwin\/frontend:..*/image: uledwin\/frontend:${{ steps.version-bump.outputs.newTag }}/' overlays/dev/frontend.deployment.yml
          cat overlays/dev/frontend.deployment.yml
          git commit -am "Update Version of Docker Image"
          git push https://uledwin:${{ secrets.API_TOKEN_GITHUB }}@github.com/uledwin/rampupk8sdeployment.git feature